version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /tools/wordpress-env
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /templates/child/admin-ui-pack-seed-basic/.wp-plugin-base-admin-ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /templates/child/admin-ui-pack-seed-dataviews/.wp-plugin-base-admin-ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /tests/fixtures/existing-application
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /tools/markdownlint
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: pip
    directory: /tools/python-lint-tools
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: pip
    directory: /tools/python-semgrep
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: composer
    directory: /templates/child/quality-pack/.wp-plugin-base-quality-pack
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: phpunit/phpunit
        update-types:
          - version-update:semver-major
  - package-ecosystem: composer
    directory: /templates/child/security-pack/.wp-plugin-base-security-pack
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
